version: "3.8"

services:
  django_recipe_api:
    build:
      context: .
    ports:
      - "8087:8000"
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: shopping_cart
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"

volumes:
  mysql_data: