version: "3.8"

services:
  django_recipe_api:
    build:
      context: .
    ports:
      - "8487:8000"
    volumes:
      - .:/shopping_cart
    command: >
      sh -c "python /shopping_cart/shopping_cart/manage.py makemigrations &&
             python /shopping_cart/shopping_cart/manage.py migrate &&
             python /shopping_cart/shopping_cart/manage.py seed_data --carts 3 &&
             python /shopping_cart/shopping_cart/manage.py runserver 0.0.0.0:8000"